{
  "formatVersion": "1.1",
  "component": {
    "group": "com.chenchen.router",
    "module": "router-gradle-plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-gradle-plugin-1.0.jar",
          "url": "router-gradle-plugin-1.0.jar",
          "size": 5826,
          "sha512": "7016392b04dbbf500aafb4f4ef2f0ca1a39ce4688aea1c8f45549abb5a8a19edd10b43bdb5cf09e1ca302f88f4c6a18d346221d09b010525459f3f2d616cfb09",
          "sha256": "89bdd4a9399aa848fa3aa14b102f5baaf4f04bf566a40872db20d4e5e88e26a7",
          "sha1": "354cb56564ff3e8984ce0872101d78d3e9f94992",
          "md5": "cae3d8ccfdc4488df6c74c40692e78c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "router-gradle-plugin-1.0.jar",
          "url": "router-gradle-plugin-1.0.jar",
          "size": 5826,
          "sha512": "7016392b04dbbf500aafb4f4ef2f0ca1a39ce4688aea1c8f45549abb5a8a19edd10b43bdb5cf09e1ca302f88f4c6a18d346221d09b010525459f3f2d616cfb09",
          "sha256": "89bdd4a9399aa848fa3aa14b102f5baaf4f04bf566a40872db20d4e5e88e26a7",
          "sha1": "354cb56564ff3e8984ce0872101d78d3e9f94992",
          "md5": "cae3d8ccfdc4488df6c74c40692e78c0"
        }
      ]
    }
  ]
}
